### ISSUE TITLE
test phptinker

### ISSUE THREAD

**Issue by aneesdev** [aneeskhan47/laravel-pagination-merge#1]
@phptinker

```php
collect(1, 2, 3, 4, 5);
```

**Comment by phptinker** [comment]
@aneesdev, here's the evaluated code:

```
Illuminate\Support\Collection {#2179
  all: [
    1,
  ],
}
```

<details>
<summary>We evaluated this code</summary>

```php
collect(1, 2, 3, 4, 5);
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.
